### ISSUE TITLE
Funcionalidad para extender el editor

### ISSUE THREAD

**Issue by DannCoco** [PlatziDev/editor#4]
Cordial saludo Sergio,

Es posible que me pueda hacer el favor de subir la funcionalidad para extender el editor?
Agradezco su colaboración.

**Comment by sergiodxa** [comment]
A que te referís con subir?

**Comment by DannCoco** [comment]
compartir por git.

**Comment by sergiodxa** [comment]
Ya está en el repositorio y en npm. Revisá el readme donde habla sobre extender el editor.
